### ISSUE TITLE
Switch to memoir

### ISSUE THREAD

**Issue by cdlm** [SquareBracketAssociates/NumericalMethods#3]
I'm trying to use the memoir class, as it provides ready-to-use support for the quotes under each chapter title. However, there are many bad uses of font commands that will need fixing…

**Comment by Ducasse** [comment]
Thanks Damien.
Pay attention that serge would like to convert the book to be in pillar.
What we should fix in priority is the figure (in fact in the book it is mentioned that we should place a figure with some grey boxes) but the figures with grey boxes was produced by the publisher using the figures didier did.

**Comment by SergeStinckwich** [comment]
Yes thanks you Damien, but don't but too much efforts on this, because we might change for Pillar in the future.

**Comment by SergeStinckwich** [comment]
No more relevant as we will use the sbabook template in the future.
